### ISSUE TITLE
@influxdata/influxdb3-client release

### ISSUE THREAD

**Issue by lmangani** [bonitoo-io/influxdb3-js#45]
### Please direct all support questions to slack or the forums. Thank you.

So much ❤️ for this flight module! You guys always rock at fluxy stuff! I'll open/close this issue purely to ask if there's a set date for the `@influxdata/influxdb3-client` package to be pushed to npm and start vanilla testing?

**Comment by bednar** [comment]
I hope today.

**Comment by bednar** [comment]
The release `v0.1.0` is released.

**Comment by lmangani** [comment]
Awesome! Let the party begin!

Is it ok to submit issues and questions about usage/testing w/ [stand alone iox](https://github.com/metrico/iox-community)?
